name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: fetch evalfile
      run: |
        wget https://github.com/cosmobobak/viridithas-networks/releases/download/zhudun/zhudun.nnue
        echo "EVALFILE=zhudun.nnue" >> $GITHUB_ENV
    - name: build and test
      run: cargo build --verbose
    - name: run tests
      run: cargo test --verbose
